#################################################
# Triggers
#################################################
trigger:
- none 
#- main

#################################################
# Agent Pool
#################################################
pool:
  vmImage: 'ubuntu-20.04'

#################################################
# Parameters
#################################################
parameters:
# TARGET_VG_ENV
- name: TARGET_VariableGroup
  type: string
  default: dev
  values:
  - dev
  
#################################################
# Variables
#################################################
variables:
- group: ${{ parameters.TARGET_VariableGroup }}

jobs:
- job: TestStart

  steps:
  - task: TerraformInstaller@0
    displayName: "Install Terraform"
    inputs:
      terraformVersion: 'latest'

  - bash: |
      cd terraform/environments/dev/
      terraform init -backend-config=backend.tf
      displayName: Terraform Init
      name: init
    env:
      ARM_ACCESS_KEY: $(ARM_ACCESS_KEY)
      ARM_CLIENT_ID: $(ARM_CLIENT_ID)
      ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
      ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
      ARM_TENANT_ID: $(ARM_TENANT_ID)

  - bash: |
      cd terraform/environments/dev/
      terraform plan
      displayName: Terraform Plan
      name: plan
    env:
      ARM_ACCESS_KEY: $(ARM_ACCESS_KEY)
      ARM_CLIENT_ID: $(ARM_CLIENT_ID)
      ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
      ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
      ARM_TENANT_ID: $(ARM_TENANT_ID)