#################################################
# Triggers
#################################################
trigger:
- none 
#- main

#################################################
# Agent Pool
#################################################
pool:
  vmImage: 'ubuntu-20.04'

#################################################
# Parameters
#################################################
parameters:
# TARGET_VG_ENV
- name: TARGET_Variable_Group
  type: string
  default: dev
  values:
  - dev
  
#################################################
# Variables
#################################################
variables:
- group: ${{ parameters.TARGET_Variable_Group }}

#################################################
# Stages
#################################################
stages:
- stage: install
  jobs:
  - job: 
    steps:
    - task: TerraformInstaller@0
      displayName: "Install Terraform"
      inputs:
        terraformVersion: 'latest'
        
- stage: validate
  jobs:
  - job: Validate
    steps:
    - bash: |
        cd terraform/environments/dev/
        terraform init
      env:
        ARM_ACCESS_KEY: $(ARM_ACCESS_KEY)
        ARM_CLIENT_ID: $(ARM_CLIENT_ID)
        ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
        ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
        ARM_TENANT_ID: $(ARM_TENANT_ID)
    dependsOn: install
      
- stage: dev_init
  jobs:
  - job: Init
    steps:
    - bash: |
        cd terraform/environments/dev/
        terraform init
      env:
        ARM_ACCESS_KEY: $(ARM_ACCESS_KEY)
        ARM_CLIENT_ID: $(ARM_CLIENT_ID)
        ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
        ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
        ARM_TENANT_ID: $(ARM_TENANT_ID)
    dependsOn: validate

- stage: dev_plan
  jobs:
  - job: Plan
    steps:
    - bash: |
        cd terraform/environments/dev/
        terraform plan
      env:
        ARM_ACCESS_KEY: $(ARM_ACCESS_KEY)
        ARM_CLIENT_ID: $(ARM_CLIENT_ID)
        ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
        ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
        ARM_TENANT_ID: $(ARM_TENANT_ID)
    dependsOn: dev_init
