#################################################
# Triggers
#################################################
trigger:
- none 
#- main

#################################################
# Agent Pool
#################################################
pool:
  vmImage: 'ubuntu-20.04'

#################################################
# Parameters
#################################################
parameters:
# TARGET_VG_ENV
- name: Environment_Variable_Group
  type: string
  default: dev
  values:
  - dev
  
#################################################
# Variables
#################################################
variables:
- group: ${{ parameters.Environment_Variable_Group }}

#################################################
# Stages
#################################################
stages:

#################################################
# DEV Stage 
#################################################
- stage: dev
  jobs:
  - job: install
    displayName: "Install Terraform"
    steps:
    - task: TerraformInstaller@0
      displayName: "Install Terraform"
      inputs:
        terraformVersion: 'latest'
  
  - job: init
    displayName: "Terraform Init"
    dependsOn: install
    steps:
    - bash: |
        cd terraform/environments/dev
        terraform init
      env:
        ARM_ACCESS_KEY: $(ARM_ACCESS_KEY)
        ARM_CLIENT_ID: $(ARM_CLIENT_ID)
        ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
        ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
        ARM_TENANT_ID: $(ARM_TENANT_ID)

  - job: validate
    displayName: "Terraform Validate"
    dependsOn: init
    steps:
    - bash: |
        cd terraform/environments/dev
        terraform validate
      env:
        ARM_ACCESS_KEY: $(ARM_ACCESS_KEY)
        ARM_CLIENT_ID: $(ARM_CLIENT_ID)
        ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
        ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
        ARM_TENANT_ID: $(ARM_TENANT_ID)

  - job: plan
    displayName: "Terraform Plan"
    dependsOn: validate
    steps:
    - bash: |
        cd terraform/environments/dev
        terraform plan
      env:
        ARM_ACCESS_KEY: $(ARM_ACCESS_KEY)
        ARM_CLIENT_ID: $(ARM_CLIENT_ID)
        ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
        ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
        ARM_TENANT_ID: $(ARM_TENANT_ID)
